# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colour', '0002_auto_20151209_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColourRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='Manual', max_length=100)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('requested', models.DateTimeField(auto_now_add=True)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colour.Colour')),
            ],
        ),
    ]
