# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_to', models.DateTimeField()),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('data', models.TextField()),
            ],
        ),
    ]
