# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colour',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
